/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'site-images': SiteImage;
    'blocked-dates': BlockedDate;
    bookings: Booking;
    enquiries: Enquiry;
    'contact-messages': ContactMessage;
    'whatsapp-leads': WhatsappLead;
    'curated-posts': CuratedPost;
    'blog-posts': BlogPost;
    testimonials: Testimonial;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'site-images': SiteImagesSelect<false> | SiteImagesSelect<true>;
    'blocked-dates': BlockedDatesSelect<false> | BlockedDatesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'whatsapp-leads': WhatsappLeadsSelect<false> | WhatsappLeadsSelect<true>;
    'curated-posts': CuratedPostsSelect<false> | CuratedPostsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('de' | 'tr' | 'ku' | 'en' | 'nl' | 'fr' | 'es')
    | ('de' | 'tr' | 'ku' | 'en' | 'nl' | 'fr' | 'es')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'de' | 'tr' | 'ku' | 'en' | 'nl' | 'fr' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Zugänge für das DJ Veys-Adminpanel. In der Regel reicht ein einziger Account.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Anzeigename im Adminpanel (optional).
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Bild-Uploads für Blog, Testimonials und die austauschbaren Bild-Slots der Website (SiteImages).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Pflichtfeld — Alt-Text für Barrierefreiheit und SEO. Pro Sprache pflegbar.
   */
  alt: string;
  /**
   * Optionale Bildunterschrift (z. B. für Blog/Testimonials).
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Jedes austauschbare Foto der Website. Was genau fotografiert werden soll, steht in docs/IMAGE-SLOTS.md (Fotografen-Briefing) — hier nur den Slot wählen, bei Bedarf eine ID anhängen (Stadt-/Artikel-Slug oder Kundenstimme) und das Bild hochladen. Kein Eintrag für einen Slot = ein gestalteter Platzhalter statt eines kaputten Bilds — nichts geht kaputt, solange hier noch nichts steht.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-images".
 */
export interface SiteImage {
  id: number;
  /**
   * Welcher Bereich der Website. Die genaue Bildvorgabe steht in docs/IMAGE-SLOTS.md.
   */
  slotKey:
    | 'home.hero.background'
    | 'home.showreel.poster'
    | 'weddings.hero.atmosphere'
    | 'gallery.hero.atmosphere'
    | 'epk.portrait'
    | 'musik.hero.performance'
    | 'home.intro.portrait'
    | 'services.wedding.image'
    | 'services.engagement.image'
    | 'services.afterparty.image'
    | 'services.corporate.image'
    | 'packages.signature.image'
    | 'epk.pressPhoto.performance'
    | 'epk.pressPhoto.hosting'
    | 'kontakt.portrait'
    | 'home.testimonials.avatar'
    | 'packages.essential.image'
    | 'packages.prestige.image'
    | 'epk.personalStory'
    | 'epk.setupDetail'
    | 'ablauf.process.image'
    | 'og.default'
    | 'city.header.background'
    | 'blog.cover'
    | 'region.header.background';
  /**
   * Nur bei dynamischen Slots ausfüllen: Stadt-Slug (z. B. "stuttgart"), Artikel-Slug oder Kundenstimme-ID. Bei allen anderen Slots leer lassen.
   */
  dynamicId?: string | null;
  /**
   * Automatisch aus Slot + ID zusammengesetzt — der exakte Schlüssel, den die Website abfragt.
   */
  key?: string | null;
  /**
   * 1 = größte Wirkung, zuerst fotografieren (aus dem Slot abgeleitet).
   */
  priority?: number | null;
  /**
   * Alt-Text ist beim Hochladen in der Medien-Sammlung Pflicht.
   */
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tage, die im öffentlichen Verfügbarkeitskalender als belegt angezeigt werden. Eine leere Liste bedeutet "unbekannt", nicht "alles frei" — siehe src/content/availability.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocked-dates".
 */
export interface BlockedDate {
  id: number;
  /**
   * Format JJJJ-MM-TT, z. B. 2026-08-14. Ein Eintrag pro Kalendertag.
   */
  date: string;
  /**
   * Nur intern sichtbar (z. B. Kundenname/Notiz) — erscheint nie auf der Website.
   */
  reason?: string | null;
  /**
   * "Aus einer Buchung" wird automatisch gesetzt/entfernt, wenn eine Buchung in diesem Panel angelegt, storniert oder gelöscht wird — bitte nicht von Hand ändern.
   */
  source: 'manual' | 'booking';
  /**
   * Verknüpfte Buchung.
   */
  booking?: (number | null) | Booking;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vom DJ selbst angelegte, bestätigte Termine. Blockiert automatisch den Tag im öffentlichen Kalender.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  /**
   * Format JJJJ-MM-TT, z. B. 2026-08-14.
   */
  date: string;
  /**
   * Interne Bezeichnung, z. B. "Hochzeit Familie Yıldız".
   */
  title: string;
  eventType: 'wedding' | 'engagement' | 'henna' | 'afterparty' | 'corporate' | 'birthday' | 'other';
  city?: string | null;
  venue?: string | null;
  customerName?: string | null;
  notes?: string | null;
  status: 'confirmed' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * Eingehende Anfragen aus dem öffentlichen Formular unter /anfrage — zum Sichten und Nachverfolgen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  status: 'new' | 'contacted' | 'won' | 'lost';
  leadScore?: number | null;
  leadTier?: ('hot' | 'warm' | 'cold') | null;
  /**
   * Sprache, in der die Anfrage abgeschickt wurde.
   */
  locale?: ('de' | 'en' | 'tr' | 'ku' | 'nl' | 'fr' | 'es') | null;
  eventDate: string;
  eventType?: ('wedding' | 'engagement' | 'henna' | 'afterparty' | 'corporate' | 'birthday' | 'other') | null;
  city: string;
  venue?: string | null;
  guests?: number | null;
  startTime?: string | null;
  endTime?: string | null;
  package?: ('essential' | 'signature' | 'prestige' | 'custom') | null;
  budget?: ('unsure' | 'a' | 'b' | 'c' | 'd') | null;
  services?: ('dj' | 'hosting' | 'liveMusic' | 'avRental')[] | null;
  hostingLanguage?: ('noPreference' | 'de' | 'tr' | 'en') | null;
  firstName: string;
  lastName: string;
  partnerName?: string | null;
  email: string;
  phone: string;
  message?: string | null;
  source?: ('google' | 'instagram' | 'recommendation' | 'venue' | 'ai' | 'other') | null;
  consent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Eingehende Nachrichten aus dem allgemeinen Kontaktformular unter /kontakt (kein Buchungsdatum).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  status: 'new' | 'read' | 'answered' | 'archived';
  /**
   * Sprache der Website beim Absenden — in dieser Sprache antworten.
   */
  locale?: ('de' | 'en' | 'tr' | 'ku' | 'nl' | 'fr' | 'es') | null;
  subject: 'general' | 'booking' | 'technical' | 'partnership' | 'press' | 'other';
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  /**
   * Firma / Location-Name, falls angegeben.
   */
  company?: string | null;
  preferredContact?: ('email' | 'phone' | 'whatsapp') | null;
  /**
   * Format JJJJ-MM-TT, falls schon ein Datum feststeht (optional).
   */
  eventDate?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Angaben aus dem WhatsApp-Vorqualifizierungs-Dialog, bevor zu wa.me weitergeleitet wird. Kein Name/E-Mail/Telefon — WhatsApp liefert den Kontaktweg selbst.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-leads".
 */
export interface WhatsappLead {
  id: number;
  leadScore?: number | null;
  leadTier?: ('hot' | 'warm' | 'cold') | null;
  source: 'fab' | 'stickyCta' | 'contactPage' | 'bookingSuccess';
  locale?: ('de' | 'en' | 'tr' | 'ku' | 'nl' | 'fr' | 'es') | null;
  eventType?: ('wedding' | 'engagement' | 'henna' | 'corporate' | 'other') | null;
  /**
   * Format JJJJ-MM-TT.
   */
  eventDate?: string | null;
  city?: string | null;
  guestsRange?: ('under80' | 'from80to150' | 'from150to250' | 'over250') | null;
  service?: ('dj' | 'djOrchestra' | 'hosting' | 'technik') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Handverlesene Instagram-/YouTube-Beiträge für die Website. Link einfügen — Plattform und (bei YouTube) Vorschaubild werden automatisch erkannt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "curated-posts".
 */
export interface CuratedPost {
  id: number;
  /**
   * Der eingefügte Instagram- oder YouTube-Link.
   */
  permalink: string;
  /**
   * Wird automatisch aus dem Link erkannt — nicht manuell änderbar.
   */
  platform: 'instagram' | 'youtube';
  /**
   * Optional — ersetzt die Original-Caption. Leer lassen, wenn keine Caption angezeigt werden soll.
   */
  captionOverride?: string | null;
  /**
   * YouTube: automatisch, kein Upload nötig — das Vorschaubild wird aus dem Link erzeugt. Instagram: ohne Meta-Zugangsdaten kann kein Bild automatisch geladen werden — bitte hier einen Screenshot/eine Kopie des Beitragsbilds hochladen, sonst erscheint nur ein Platzhalter.
   */
  thumbnail?: (number | null) | Media;
  /**
   * Wird zuerst angezeigt, plattformübergreifend.
   */
  featured?: boolean | null;
  /**
   * Manuelle Reihenfolge (aufsteigend) nach "Featured". Leer lassen für Sortierung nach Kuratierungsdatum.
   */
  sortOrder?: number | null;
  status: 'draft' | 'published';
  /**
   * Wo dieser Beitrag erscheinen soll. Werte müssen exakt zu SocialPlacement in src/lib/social/types.ts passen.
   */
  placement: ('home' | 'gallery' | 'contact')[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Artikel für /ratgeber ("Guide"). Nur "Veröffentlicht" ist öffentlich sichtbar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL-Segment, pro Sprache eigen — z. B. "hochzeits-dj-checkliste" / "wedding-dj-checklist".
   */
  slug: string;
  /**
   * Kurzfassung für Teaser-Karten und Meta-Description.
   */
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  tags?: string[] | null;
  /**
   * Anzeigedatum — kann in die Zukunft gelegt werden.
   */
  publishedAt?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Kundenstimmen für die Website. Nur "Veröffentlicht" ist öffentlich sichtbar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  authorName: string;
  /**
   * Datum der Feier (optional).
   */
  eventDate?: string | null;
  venue?: string | null;
  quote: string;
  /**
   * 1–5 Sterne, falls bekannt. Ab drei bewerteten Stimmen erscheint die Sterne-Auszeichnung in Google.
   */
  rating?: number | null;
  coverImage?: (number | null) | Media;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'site-images';
        value: number | SiteImage;
      } | null)
    | ({
        relationTo: 'blocked-dates';
        value: number | BlockedDate;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'whatsapp-leads';
        value: number | WhatsappLead;
      } | null)
    | ({
        relationTo: 'curated-posts';
        value: number | CuratedPost;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-images_select".
 */
export interface SiteImagesSelect<T extends boolean = true> {
  slotKey?: T;
  dynamicId?: T;
  key?: T;
  priority?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocked-dates_select".
 */
export interface BlockedDatesSelect<T extends boolean = true> {
  date?: T;
  reason?: T;
  source?: T;
  booking?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  date?: T;
  title?: T;
  eventType?: T;
  city?: T;
  venue?: T;
  customerName?: T;
  notes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  status?: T;
  leadScore?: T;
  leadTier?: T;
  locale?: T;
  eventDate?: T;
  eventType?: T;
  city?: T;
  venue?: T;
  guests?: T;
  startTime?: T;
  endTime?: T;
  package?: T;
  budget?: T;
  services?: T;
  hostingLanguage?: T;
  firstName?: T;
  lastName?: T;
  partnerName?: T;
  email?: T;
  phone?: T;
  message?: T;
  source?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  status?: T;
  locale?: T;
  subject?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  company?: T;
  preferredContact?: T;
  eventDate?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-leads_select".
 */
export interface WhatsappLeadsSelect<T extends boolean = true> {
  leadScore?: T;
  leadTier?: T;
  source?: T;
  locale?: T;
  eventType?: T;
  eventDate?: T;
  city?: T;
  guestsRange?: T;
  service?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "curated-posts_select".
 */
export interface CuratedPostsSelect<T extends boolean = true> {
  permalink?: T;
  platform?: T;
  captionOverride?: T;
  thumbnail?: T;
  featured?: T;
  sortOrder?: T;
  status?: T;
  placement?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  coverImage?: T;
  tags?: T;
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  authorName?: T;
  eventDate?: T;
  venue?: T;
  quote?: T;
  rating?: T;
  coverImage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Kontakt, Adresse, Social Links, Kennzahlen und Sprechstunden der Website. Leer gelassene Felder behalten den bisherigen Standardwert aus dem Code (site.ts) — ein Tippfehler blockiert also nie den ganzen Kontaktweg.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  contact?: {
    /**
     * Überschreibt site.contact.email.
     */
    email?: string | null;
    /**
     * Anzeigeformat, z. B. "+49 176 64844815".
     */
    phone?: string | null;
    /**
     * tel:-Link. Wird aus "phone" abgeleitet, wenn leer — kann aber überschrieben werden.
     */
    phoneHref?: string | null;
    /**
     * Nur Ziffern inkl. Ländercode für wa.me-Links, z. B. "4917664844815".
     */
    whatsapp?: string | null;
  };
  /**
   * Vollständige Anschrift nach § 5 DDG. Straße UND Postleitzahl sind zwingend — nur der Ort genügt nicht und ist abmahnfähig. Solange beide fehlen, zeigt die Impressum-Seite an dieser Stelle sichtbar einen Platzhalter statt einer erfundenen Adresse.
   */
  address?: {
    street?: string | null;
    postalCode?: string | null;
    city?: string | null;
  };
  /**
   * Pflichtangaben für den deutschen Rechtsraum. Diese Felder werden ausschließlich hier gepflegt — kein Code-Deploy nötig. Nichts erfinden: leer gelassene Felder erscheinen auf der Impressum-Seite als sichtbarer Platzhalter, und das ist einer falschen Angabe deutlich vorzuziehen.
   */
  legal?: {
    /**
     * Nach § 27a UStG anzugeben, sofern vorhanden. Wer die Kleinunternehmerregelung nutzt, lässt das Feld leer und setzt stattdessen den Haken unten.
     */
    vatId?: string | null;
    /**
     * Setzen, wenn keine Umsatzsteuer ausgewiesen wird. Die Impressum-Seite formuliert daraus den Hinweis. Entweder dieses Häkchen oder eine USt-IdNr. muss gesetzt sein — beides leer ist rechtlich unvollständig.
     */
    smallBusinessExempt?: boolean | null;
    /**
     * Versicherer und räumlicher Geltungsbereich. Für DJ-/Veranstaltungsdienstleistungen üblich und von vielen Locations verlangt.
     */
    professionalInsurance?: string | null;
  };
  social?: {
    instagram?: string | null;
    instagramHandle?: string | null;
    instagramLegacy?: string | null;
    youtube?: string | null;
    googleMaps?: string | null;
    tiktok?: string | null;
    spotify?: string | null;
    soundcloud?: string | null;
    mixcloud?: string | null;
  };
  /**
   * Regelmäßig bespielte Städte, z. B. "Stuttgart". Überschreibt die komplette Liste, wenn nicht leer.
   */
  serviceAreas?: string[] | null;
  stats?: {
    yearsExperience?: number | null;
    eventsCompleted?: number | null;
    instagramFollowers?: number | null;
    hostingLanguages?: ('de' | 'tr' | 'en')[] | null;
  };
  season?: {
    /**
     * Aktuelle Buchungssaison, z. B. 2026.
     */
    year?: number | null;
  };
  /**
   * Das Badge und das AggregateRating-Schema erscheinen nur, wenn sowohl "count" > 0 als auch "rating" > 0 sind — niemals eine erfundene Bewertungszahl eintragen (siehe BRAND-FACTS.md).
   */
  reviews?: {
    googlePlaceId?: string | null;
    rating?: number | null;
    count?: number | null;
    profileUrl?: string | null;
  };
  /**
   * Wann Veysel erreichbar ist. Für "nach Vereinbarung" o.ä. das Feld "Hinweis" nutzen statt Zeiten.
   */
  openingHours?:
    | {
        weekday: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
        opens?: string | null;
        closes?: string | null;
        closed?: boolean | null;
        /**
         * Optional, z. B. "Termine nach Vereinbarung".
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        phoneHref?: T;
        whatsapp?: T;
      };
  address?:
    | T
    | {
        street?: T;
        postalCode?: T;
        city?: T;
      };
  legal?:
    | T
    | {
        vatId?: T;
        smallBusinessExempt?: T;
        professionalInsurance?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        instagramHandle?: T;
        instagramLegacy?: T;
        youtube?: T;
        googleMaps?: T;
        tiktok?: T;
        spotify?: T;
        soundcloud?: T;
        mixcloud?: T;
      };
  serviceAreas?: T;
  stats?:
    | T
    | {
        yearsExperience?: T;
        eventsCompleted?: T;
        instagramFollowers?: T;
        hostingLanguages?: T;
      };
  season?:
    | T
    | {
        year?: T;
      };
  reviews?:
    | T
    | {
        googlePlaceId?: T;
        rating?: T;
        count?: T;
        profileUrl?: T;
      };
  openingHours?:
    | T
    | {
        weekday?: T;
        opens?: T;
        closes?: T;
        closed?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}