import type { MetadataRoute } from 'next';
import { site } from '@/content/site';

/**
 * PWA manifest for veysl.de. Colors match the dark/gold palette from
 * globals.css (`--color-bg` / `--color-gold`) — kept as literal hex here since
 * the manifest is served as static JSON and can't consume CSS custom
 * properties.
 *
 * Icon files referenced below do NOT exist yet. See the SEO agent report for
 * the exact asset spec (sizes, maskable safe-zone) the client/designer needs
 * to deliver. Referencing the conventional paths now means nothing else has
 * to change once they land — no PNGs are generated by this file.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${site.name} — ${site.tagline.de}`,
    short_name: site.name,
    description: site.tagline.de,
    start_url: '/',
    scope: '/',
    display: 'standalone',
    background_color: '#08080A',
    theme_color: '#D6B36A',
    lang: 'de',
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-192-maskable.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: '/icons/icon-512-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
